# deployment/android/screenshots/lane.rb
# Android screenshot pipeline — AI-generated screenshots.
#
# Screenshots are generated by Claude intelligence (via /release) and placed
# directly into the metadata images directory as PNG files. No Espresso,
# screengrab, or emulator infrastructure required.
#
# Lanes:
#   upload_android_screenshots — upload screenshots to Google Play Store via supply
#   android_screenshots        — alias for upload_android_screenshots

ANDROID_SCREENSHOTS_PATH = File.expand_path("../metadata/images", __dir__).freeze

platform :android do
  desc "Upload Android screenshots + feature graphic to Google Play Store (all active locales)"
  lane :upload_android_screenshots do
    # supply's upload_to_play_store requires an existing release in the track,
    # which makes it unusable for fresh apps or listing-only updates.
    # The direct-API script bypasses this limitation via edits.images.upload.
    repo_root = File.expand_path("../../..", __dir__)
    sh("bash #{repo_root}/scripts/store/sync-play-listing.sh")
    UI.success("✅ Android screenshots + store listing uploaded to Play Store")
  end

  desc "Sync full Play Store listing (text + screenshots + feature graphic)"
  lane :sync_play_listing do
    repo_root = File.expand_path("../../..", __dir__)
    sh("bash #{repo_root}/scripts/store/sync-play-listing.sh")
  end

  desc "Alias for upload_android_screenshots"
  lane :android_screenshots do
    upload_android_screenshots
  end
end
