# deployment/ios/screenshots/lane.rb
# iOS screenshot pipeline — AI-generated screenshots.
#
# Screenshots are generated by Claude intelligence (via /release) and placed
# directly into the metadata screenshots directory as PNG files. No XCUITest
# or simulator infrastructure required.
#
# Lanes:
#   generate_ios_screenshots   — placeholder lane; actual generation is done by
#                                Claude intelligence invoked from /release
#   frame_ios_screenshots      — wrap PNGs in device frames via frameit
#   upload_ios_screenshots     — upload framed screenshots to App Store Connect
#   ios_screenshots            — frame + upload (generation is a /release step)

FRAMEFILE_PATH       = File.expand_path("Framefile.json", __dir__).freeze
# __dir__ is deployment/ios/screenshots — up ONE level is deployment/ios, then appstore/metadata/
# screenshots. The old "../../appstore/..." went up TWO levels to deployment/appstore/... (a nonexistent
# sibling), so deliver's screenshots_path pointed at an empty dir and "uploaded all" ZERO screenshots
# (silent vacuous success). (2026-08-10 — matches config.rb's deployment/ios/appstore/metadata/screenshots.)
IOS_SCREENSHOTS_PATH = File.expand_path("../appstore/metadata/screenshots", __dir__).freeze

platform :ios do
  desc "Frame iOS screenshots with device bezels via frameit"
  lane :frame_ios_screenshots do
    frameit(
      path:          IOS_SCREENSHOTS_PATH,
      framefile:     FRAMEFILE_PATH,
      use_legacy_iphone5s: false,
      use_legacy_iphone6s: false,
    )
    UI.success("✅ iOS screenshots framed → #{IOS_SCREENSHOTS_PATH}")
  end

  desc "Upload framed iOS screenshots to App Store Connect"
  lane :upload_ios_screenshots do |options|
    setup_ci_if_needed
    load_api_key(options)

    ios_config      = FastlaneConfig::IosConfig::BUILD_CONFIG
    appstore_config = FastlaneConfig::IosConfig::APPSTORE_CONFIG

    deliver(
      api_key:              Actions.lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
      metadata_path:        ios_config[:metadata_path],
      screenshots_path:     IOS_SCREENSHOTS_PATH,
      skip_binary_upload:   true,
      skip_metadata:        true,
      skip_screenshots:     false,
      overwrite_screenshots: true,
      # metadata/ holds the screenshots/ subdir + review_information/ + per-device scaffolding dirs that
      # are NOT ASC locale folders; without this deliver aborts "Unsupported directory name(s)". Matches
      # the promoteToAppStore lane (deployment/ios/appstore/lane.rb) which sets the same flag.
      ignore_language_directory_validation: true,
      # Screenshots-only upload — never run precheck (it can't check In-App Purchases with an ASC API key
      # and would fail the lane after a successful screenshot upload). We are not submitting for review.
      run_precheck_before_submit: false,
      # A version already "Waiting for Review" LOCKS its screenshots ("Can't Delete Screenshot After
      # Submit for review"). Reject it back to Prepare-for-Submission so the corrected screenshots can
      # replace the stale set; the version is then editable + re-submittable. (2026-08-10)
      reject_if_possible: true,
      force:                appstore_config[:force],
    )

    UI.success("✅ iOS screenshots uploaded to App Store Connect")
  end

  desc "Frame + upload iOS screenshots (generation is handled by /release)"
  lane :ios_screenshots do |options|
    frame_ios_screenshots
    upload_ios_screenshots(options)
  end
end
