# deployment/desktop/mac-app-store/screenshots/lane.rb
# macOS screenshot pipeline — AI-generated screenshots.
#
# Screenshots are generated by Claude intelligence (via /release) and placed
# directly into the metadata screenshots directory as PNG files. No Compose
# Desktop UI tests, AWT Robot, or Gradle task infrastructure required.
#
# Lanes:
#   upload_macos_screenshots   — upload screenshots to Mac App Store via deliver
#   macos_screenshots          — alias for upload_macos_screenshots

platform :mac do
  desc "Upload macOS screenshots to Mac App Store via deliver"
  lane :upload_macos_screenshots do |options|
    setup_ci_if_needed

    deliver(
      platform:               "osx",
      api_key:                Actions.lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
      app_identifier:         ENV["MAC_APP_IDENTIFIER"] || ENV["MAC_BUNDLE_ID"] || ForkIdentity::APP_ID,
      metadata_path:          MAC_APP_STORE_METADATA_PATH,
      screenshots_path:       MAC_APP_STORE_SCREENSHOTS_PATH,
      primary_locale:         MAC_APP_STORE_PRIMARY_LOCALE,
      skip_binary_upload:     true,
      skip_metadata:          true,
      skip_screenshots:       false,
      overwrite_screenshots:  true,
      force:                  true,
    )

    UI.success("✅ macOS screenshots uploaded to Mac App Store")
  end

  desc "Upload macOS screenshots (generation is handled by /release)"
  lane :macos_screenshots do |options|
    upload_macos_screenshots(options)
  end
end
