/*
 * Copyright 2024 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See https://github.com/openMF/mobile-wallet/blob/master/LICENSE.md
 */
package org.mifospay.core.common

/**
 * Created by naman on 17/6/17.
 */
object Constants {
    const val BASIC = "Basic "
    const val CLIENT_ID = "client_id"
    const val ACCOUNT_ID = "account_id"
    const val ACCOUNT = "account"
    const val TO_EXTERNAL_ID = "to_external_id"
    const val RUPEE = "₹"
    const val QR_DATA = "qr_data"
    const val MERCHANT_NAME = "merchant_name"
    const val MERCHANT_VPA = "merchant_vpa"
    const val MERCHANT_ACCOUNT_NO = "merchant_account_no"
    const val FILE = "file"
    const val MULTIPART_FORM_DATA = "multipart/form-data"
    const val CHOOSE_A_FILE_TO_UPLOAD = "Choose a file to upload."
    const val ERROR_UPLOADING_DOCS = "Error uploading docs."
    const val KYC_LEVEL_2_DOCUMENTS_ADDED_SUCCESSFULLY = "KYC Level 2 documents added successfully."
    const val IMAGE = "image/*"
    const val APPLICATION_PDF = "application/pdf"
    const val ERROR_ADDING_KYC_LEVEL_1_DETAILS = "Error adding KYC Level 1 details."
    const val KYC_LEVEL_1_DETAILS_ADDED_SUCCESSFULLY = "KYC Level 1 details added successfully."
    const val PLEASE_WAIT = "Please wait.."
    const val COMPLETE_KYC = "Complete KYC"
    const val NEED_EXTERNAL_STORAGE_PERMISSION_TO_BROWSE_DOCUMENTS =
        "Need external storage permission to browse documents."
    const val CHOOSE_FILE = "Choose File"
    const val KYC_REGISTRATION_LEVEL_2 = "KYC Registration Level 2"
    const val KYC_REGISTRATION_LEVEL_1 = "KYC Registration Level 1"
    const val DD_MM_YY = "dd/MM/yy"
    const val ERROR_DELETING_CARD = "Error deleting card."
    const val CARD_DELETED_SUCCESSFULLY = "Card deleted successfully."
    const val DELETING_CARD = "Deleting Card.."
    const val ERROR_UPDATING_CARD = "Error updating card."
    const val CARD_UPDATED_SUCCESSFULLY = "Card updated successfully."
    const val INVALID_CREDIT_CARD_NUMBER = "Invalid Credit Card Number"
    const val UPDATING_CARD = "Updating Card.."
    const val ERROR_ADDING_CARD = "Error adding card."
    const val CARD_ADDED_SUCCESSFULLY = "Card added successfully."
    const val ADDING_CARD = "Adding Card.."
    const val ADD_CARD_DIALOG = "Add Card Dialog"
    const val EDIT_CARD_DIALOG = "Edit Card Dialog"
    const val SAVED_CARDS = "Saved Cards"
    const val UPDATE = "Update"
    const val KYC_REGISTRATION_LEVEL_3 = "KYC Registration Level 3"
    const val OK = "OK"
    const val SCAN_CODE = "Scan code"
    const val QR_CODE = "QR code"
    const val FAILED_TO_WRITE_DATA_TO_QR = "Failed to write data to qr"
    const val ERROR_OCCURRED = "Error occurred"
    const val LOGGING_IN = "Logging in.."
    const val HOME = "Home"
    const val PROFILE = "Profile"
    const val ERROR_FETCHING_BALANCE = "Error fetching balance"
    const val UNABLE_TO_PROCESS_TRANSFER = "Unable to process transfer"
    const val TRANSACTION_SUCCESSFUL = "Transaction successful"
    const val SENDING_MONEY = "Sending money..."
    const val INSUFFICIENT_BALANCE = "Insufficient balance"
    const val ERROR_FINDING_VPA = "Error finding Virtual Payment Address"
    const val ERROR_FINDING_MOBILE_NUMBER = "Error finding Mobile Number"
    const val PLEASE_ENTER_VALID_AMOUNT = "Please enter a valid amount"
    const val VPA_VALIDATION_REGEX = "^\\w.+@\\w+$"
    const val SELF_ACCOUNT_ERROR = "Self Account transfer is not allowed"
    const val PLEASE_ENTER_AMOUNT = "Please enter a valid amount before making the transfer"
    const val NEED_READ_CONTACTS_PERMISSION = "Need read contacts permission"
    const val NEED_CAMERA_PERMISSION_TO_SCAN_QR_CODE = "Need camera permission to scan qr code."
    const val ERROR_CHOOSING_CONTACT = "Error choosing contact"
    const val MAKE_TRANSFER_FRAGMENT = "Make Transfer Fragment"
    const val PLEASE_ENTER_ALL_THE_FIELDS = "Please enter all the fields"
    const val TRANSFER = "Transfer"
    const val TRANSACTION_DETAILS = "Transaction Details"
    const val ACCOUNT_NUMBER = "Account Number : "
    const val TRANSACTION = "transaction"
    const val TRANSACTIONS_HISTORY = "Transactions History History"
    const val SPECIFIC_TRANSACTIONS = "Specific Transactions History"
    const val HISTORY_NOT_AVAILABLE = "No Transaction History Available"
    const val RECEIPT_DOMAIN = "https://receipt.mifospay.com/"
    const val OTHER = "Other"
    const val CREDIT = "Credit"
    const val DEBIT = "Debit"
    const val RECEIPT_ID = "Receipt ID"
    const val DATE = "Date"
    const val TRANSACTION_ID = "Transaction ID"
    const val TRANSACTIONS = "transactions"
    const val ERROR_FETCHING_TRANSACTIONS = "Error fetching transactions"
    const val TRANSFER_DETAILS = "transfer details"
    const val UNIQUE_PAYMENT_LINK_COPIED_TO_CLIPBOARD = "Unique Payment Link copied to clipboard"
    const val UNIQUE_PAYMENT_LINK = "Unique Payment Link"
    const val STATUS = "Status"
    const val UNIQUE_RECEIPT_LINK_COPIED_TO_CLIPBOARD = "Unique Receipt Link copied to clipboard"
    const val UNIQUE_RECEIPT_LINK = "Unique Receipt Link"
    const val DONE = "Done"
    const val PENDING = "Pending"
    const val ITEMS = "Item(s)"
    const val AMOUNT = "Amount"
    const val INR = "INR"
    const val CONSUMER = "Consumer"
    const val MERCHANT = "Merchant"
    const val INVOICE = "Invoice"
    const val NEED_EXTERNAL_STORAGE_PERMISSION_TO_DOWNLOAD_RECEIPT =
        "Need external storage permission to download receipt"
    const val RECEIPT_DOWNLOADED_SUCCESSFULLY = "Receipt Downloaded Successfully"
    const val ERROR_DOWNLOADING_RECEIPT = "Error downloading receipt"
    const val MIFOSPAY = "mifospay"
    const val RECEIPT = "Receipt"
    const val PDF = ".pdf"
    const val ERROR_FETCHING_RECEIPT = "Error fetching receipt"
    const val INVOICE_DOMAIN = "https://invoice.mifospay.com/"
    const val SENDING_OTP_TO_YOUR_MOBILE_NUMBER = "Sending OTP to your mobile number.."
    const val MOBILE_NUMBER = "Mobile Number"
    const val COUNTRY = "Country"
    const val GOOGLE_SIGN_IN_FAILED = "Google Sign in failed."
    const val GOOGLE_GIVEN_NAME = "GOOGLE_GIVEN_NAME"
    const val GOOGLE_FAMILY_NAME = "GOOGLE_FAMILY_NAME"
    const val GOOGLE_EMAIL = "GOOGLE_EMAIL"
    const val GOOGLE_DISPLAY_NAME = "GOOGLE_DISPLAY_NAME"
    const val GOOGLE_PHOTO_URI = "GOOGLE_PHOTO_URI"
    const val CHOOSE_SIGNUP_METHOD = "Choose Signup Method"
    const val LOGGING_OUT = "Logging out..."
    const val NEED_EXTERNAL_STORAGE_PERMISSION_TO_BROWSE_IMAGES =
        "Need external storage permission to browse images"
    const val SETTINGS = "Settings"
    const val EDIT_PROFILE = "Edit Profile"
    const val FAQ = "Frequent Asked Questions"
    const val LINKED_BANK_ACCOUNTS = "Linked Bank Accounts"
    const val BANK_ACCOUNT_DETAILS = "Bank Account Details"
    const val NEW_BANK_ACCOUNT = "newBankAccount"
    const val VERIFYING_MOBILE_NUMBER = "Verifying mobile number.."
    const val VERIFYING_OTP = "Verifying Otp.."
    const val MIFOS_SAVINGS_PRODUCT_ID = "Mifos Savings Product Id"
    const val MERCHANTS = "Merchants"
    const val UPI_PIN = "UPI PIN"
    const val STEP = "step"
    const val TYPE = "Type"
    const val SETUP = "Setup"
    const val BANK_DELETED_SUCCESSFULLY = "Bank deleted successfully"
    const val ERROR_OCCURRED_WHILE_CHANGING_UPI_PIN = "Error occurred while changing UPI PIN"
    const val SETUP_UPI = "Setup UPI"
    const val ERROR_WHILE_SETTING_UP_UPI_PIN = "Error while setting up UPI PIN"
    const val UPI_PIN_SETUP_COMPLETED_SUCCESSFULLY = "UPI PIN Setup Completed Successfully"
    const val FORGOT = "Forgot"
    const val CHANGE = "Change"
    const val OTP = "otp"
    const val SETUP_UPI_PIN = "Setup UPI PIN"
    const val SETTING_UP_UPI_PIN = "Setting up UPI PIN.."
    const val UPDATED_BANK_ACCOUNT = "Updated Bank Account"
    const val INDEX = "Index"
    const val CHANGE_UPI_PIN = "Change UPI PIN"
    const val FORGOT_UPI_PIN = "Forgot UPI PIN"

    // broadcast receiver intent filters
    const val REGISTRATION_COMPLETE = "registrationComplete"
    const val PUSH_NOTIFICATION = "pushNotification"

    // id to handle the notification in the notification tray
    const val NOTIFICATION_ID = 100
    const val NOTIFICATION_ID_BIG_IMAGE = 101
    const val ERROR_FIELDS_CANNOT_BE_EMPTY = "Fields cannot be empty"
    const val ERROR_VALIDATING_PASSWORD = "Passwords are not the same"
    const val ERROR_PASSWORDS_CANT_BE_SAME = "New password can't be the same as old password."
    const val CHANGE_PROFILE_IMAGE_KEY = "CHANGE_PROFILE_IMAGE_KEY"
    const val CHANGE_PROFILE_IMAGE_VALUE = "CHANGE_PROFILE_IMAGE_VALUE"
    const val TAP_TO_REVEAL = "Tap to Reveal"
    const val NAME = "Name : "
    const val ERROR_FETCHING_TRANSACTION_DETAILS = "Error fetching details"

    // const val WHITE_BACK_BUTTON = R.drawable.ic_arrow_back_white_24dp
    //  const val BLACK_BACK_BUTTON = R.drawable.ic_arrow_back_black_24dp
    const val VIEW = "View"
    const val CURRENT_PASSCODE = "current passcode"
    const val UPDATE_PASSCODE = "update passcode"
    const val SELECT_DATE = "SELECT DATE"
    const val SI_ID = "standing_instruction_id"
    const val UNAUTHORIZED_ERROR = "401 Unauthorized"
    const val RECEIPT_SHARING_MESSAGE = "Receipt link for the transaction "
    const val TO = " to "
    const val COLON = " : "
    const val REQUEST_CAMERA = 0
    const val SCAN_QR_REQUEST_CODE = 666
}
