/*
 * ╔══════════════════════════════════════════════════════════════════════════════╗
 * ║  LOCAL FLAVORS — consumer extension point (NOT synced from kmp-project-template) ║
 * ╚══════════════════════════════════════════════════════════════════════════════╝
 *
 * This file is excluded from sync-dirs.sh and survives every upstream sync.
 * Use it to add dimensions, flavors, or overrides on top of the base contract
 * defined in KMPFlavorsConventionPlugin.kt (demo + prod × debug + staging + release).
 *
 * HOW TO USE
 * ──────────
 * 1. Uncomment the block(s) below that apply to your fork.
 * 2. Rename "bank" / "bankA" / "bankB" to your own dimension / flavor names.
 * 3. Fill in the real values (applicationId suffixes, URLs, feature flags, etc.).
 * 4. Run `./gradlew :cmp-shared:generateIosFlavorXcconfigs` once — iOS xcconfigs
 *    regenerate automatically from that point on every Xcode build.
 *
 * ALL WIRING IS AUTOMATIC — nothing else needs to be changed:
 *   Android  →  AGP productFlavors wired by AgpProductFlavorRegistrar
 *   iOS      →  xcconfigs regenerated by generateIosFlavorXcconfigs task
 *   Desktop  →  dock name / bundle ID resolved from desktopWindowTitleSuffix / applicationIdSuffix
 *   Web      →  <title> resolved from webTitleSuffix
 *
 * BUILD-TIME FLAVOR SELECTION (desktop + web):
 *   Default flavor  →  the one with isDefault.set(true) — no extra flag needed
 *   Explicit select →  ./gradlew -PkmpFlavor=bankA :cmp-desktop:packageDmg
 *
 * MULTI-DIMENSION (two or more dimensions active):
 *   Pass one -P flag per dimension:
 *   ./gradlew -PkmpFlavor=demo -PkmpFlavorBank=bankA :cmp-desktop:packageDmg
 *   Then extend the windowTitle / webTitle computation in cmp-desktop/build.gradle.kts
 *   and cmp-web/build.gradle.kts to combine suffixes from both active flavor configs.
 *
 * See docs/FLAVORS_EXTENSION.md for more recipes (signing configs, language tiers, etc.).
 */

package local

import com.mobilebytelabs.kmpflavors.KmpFlavorExtension
import org.gradle.api.Project

object LocalFlavors {
    @JvmStatic
    fun apply(ext: KmpFlavorExtension, project: Project) {

        // ── Example: add a second "bank" dimension with two flavors ─────────────
        //
        // Uncomment this entire block and rename "bank" / "bankA" / "bankB" to
        // your own dimension and flavor names. Fill in real values before building.
        //
        // ext.flavorDimensions.register("bank") { priority.set(1) }
        //
        // ext.flavors.register("bankA") {
        //     dimension.set("bank")
        //     isDefault.set(true)                          // default when no -PkmpFlavorBank flag
        //     applicationIdSuffix.set(".banka")            // Android applicationId + macOS bundle ID
        //     bundleIdSuffix.set(".banka")                 // iOS xcconfig PRODUCT_BUNDLE_IDENTIFIER
        //     desktopWindowTitleSuffix.set(" (Bank A)")    // dock name, package name, Windows menu
        //     webTitleSuffix.set(" (Bank A)")              // HTML <title> and OG tags
        //     buildConfigField("String", "BANK_URL", "\"https://api.banka.com\"")
        //     buildConfigField("String", "BANK_NAME", "\"Bank A\"")
        // }
        //
        // ext.flavors.register("bankB") {
        //     dimension.set("bank")
        //     applicationIdSuffix.set(".bankb")
        //     bundleIdSuffix.set(".bankb")
        //     desktopWindowTitleSuffix.set(" (Bank B)")
        //     webTitleSuffix.set(" (Bank B)")
        //     buildConfigField("String", "BANK_URL", "\"https://api.bankb.com\"")
        //     buildConfigField("String", "BANK_NAME", "\"Bank B\"")
        // }
        // ────────────────────────────────────────────────────────────────────────
    }
}
