/*
 * Copyright 2024 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See https://github.com/openMF/mobile-wallet/blob/master/LICENSE.md
 */

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.dependencies
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension
import org.mifospay.libs
import java.io.File

class SupabaseConfigConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        with(target) {
            val generatedDir = layout.buildDirectory.dir("generated/supabase")
            val secretsFile = rootProject.file("secrets/supabaseCredentialsFile.json")

            // Register the code generation task
            val generateTask = tasks.register("generateSupabaseConfig") {
                val outputFile = generatedDir.get().asFile
                    .resolve("org/mifospay/core/network/config/SupabaseCredentials.kt")

                // Track file content as input property for proper up-to-date checking
                // This handles both file changes and file existence changes
                val fileContent = if (secretsFile.exists() && secretsFile.length() > 0) {
                    secretsFile.readText()
                } else {
                    ""
                }
                inputs.property("credentialsContent", fileContent)
                outputs.file(outputFile)

                doLast {
                    val currentContent = inputs.properties["credentialsContent"] as String
                    val (url, anonKey) = if (currentContent.isNotEmpty()) {
                        try {
                            parseCredentials(currentContent)
                        } catch (e: Exception) {
                            logger.warn("Failed to parse Supabase credentials file: ${e.message}")
                            Pair("", "")
                        }
                    } else {
                        logger.warn("Supabase credentials file not found at: ${secretsFile.absolutePath}")
                        logger.warn("Create secrets/supabaseCredentialsFile.json with 'url' and 'anonKey' fields")
                        Pair("", "")
                    }

                    outputFile.parentFile.mkdirs()
                    val isConfigured = url.isNotBlank() && anonKey.isNotBlank()

                    outputFile.writeText(
                        """
                        |/*
                        | * Copyright 2026 Mifos Initiative
                        | *
                        | * This Source Code Form is subject to the terms of the Mozilla Public
                        | * License, v. 2.0. If a copy of the MPL was not distributed with this
                        | * file, You can obtain one at https://mozilla.org/MPL/2.0/.
                        | *
                        | * See https://github.com/openMF/mobile-wallet/blob/master/LICENSE.md
                        | */
                        |package org.mifospay.core.network.config
                        |
                        |/**
                        | * Generated Supabase credentials from secrets/supabaseCredentialsFile.json
                        | * DO NOT EDIT - This file is generated by SupabaseConfigConventionPlugin
                        | */
                        |object SupabaseCredentials {
                        |    const val URL: String = "$url"
                        |    const val ANON_KEY: String = "$anonKey"
                        |    const val isConfigured: Boolean = $isConfigured
                        |}
                        """.trimMargin()
                    )
                }
            }

            // Configure the Kotlin Multiplatform extension
            extensions.configure<KotlinMultiplatformExtension> {
                sourceSets.named("commonMain") {
                    kotlin.srcDir(generatedDir)
                    dependencies {
                        implementation(libs.findLibrary("supabase-postgrest").get())
                    }
                }
            }

            // Make compile and KSP tasks depend on the generate task
            tasks.matching {
                it.name.startsWith("compileKotlin") || it.name.startsWith("ksp")
            }.configureEach {
                dependsOn(generateTask)
            }
        }
    }

    /**
     * Simple JSON parser for extracting url and anonKey fields.
     * Avoids dependency on kotlinx-serialization in build-logic.
     */
    private fun parseCredentials(jsonContent: String): Pair<String, String> {
        val urlPattern = """"url"\s*:\s*"([^"]*)"""".toRegex()
        val anonKeyPattern = """"anonKey"\s*:\s*"([^"]*)"""".toRegex()

        val url = urlPattern.find(jsonContent)?.groupValues?.getOrNull(1) ?: ""
        val anonKey = anonKeyPattern.find(jsonContent)?.groupValues?.getOrNull(1) ?: ""

        return Pair(url, anonKey)
    }
}
