# deployment/_shared/project_config.rb — single source of truth for FastlaneConfig.
#
# Fork identity flows from three sources (highest priority first):
#   1. ENV vars              — CI injection; always checked first.
#   2. gradle/fork.properties — committed template, gitignored values; run ./gradlew syncForkConfig after edits.
#   3. local.properties     — auto-generated by syncForkConfig (fallback when fork.properties absent).
#
# To configure for local development:
#   1. cp gradle/fork.properties.template gradle/fork.properties
#   2. Fill in your values.
#   3. Run:  ./gradlew syncForkConfig
#   4. Run Fastlane as normal.
#
# For CI: set ENV vars directly — fork.properties is gitignored and not needed on CI.
#         The 6 build-time TOML values (appId etc.) are always available (committed).
#         Fastlane bridge: local.properties is written by syncForkConfig before Fastlane runs.
#
# Key name format: dot-notation matching fork.properties
#   FORK["org.email"]                  (was FORK["orgEmail"] in the old TOML-based layout)
#   FORK["firebase.android.prod.app.id"] (was FORK["firebaseAndroidProdAppId"])
#
# Consumed by:
#   - fastlane-config/project_config.rb  (shim — keeps deployment/Appfile working)
#   - fastlane/Appfile                   (direct require)
#   - fastlane/Fastfile                  (direct require — exposes constants to lanes)
#   - deployment/Fastfile                (via Appfile load-order: Appfile runs first)

require_relative "lib/build_secrets"   # secrets path resolver (secrets/LAYOUT.yaml SoT — no static paths)

module FastlaneConfig
  module ProjectConfig

    # ── Fork identity loader ─────────────────────────────────────────────────────
    # Reads gradle/fork.properties (dot-notation keys) with local.properties fallback.
    # Also seeds the 4 build-time fields from libs.versions.toml (always committed).
    #
    def self.load_fork_identity
      fork_path  = File.expand_path("../../../gradle/fork.properties", __FILE__)
      props_path = File.expand_path("../../../local.properties", __FILE__)
      toml_path  = File.expand_path("../../../gradle/libs.versions.toml", __FILE__)

      result = {}

      # 1. Seed from libs.versions.toml (always committed — provides appId etc.)
      if File.exist?(toml_path)
        toml = parse_toml_versions(toml_path)
        result["app.id"]           = toml["appId"]          if toml["appId"]
        result["app.display.name"] = toml["appDisplayName"] if toml["appDisplayName"]
        result["project.name"]     = toml["projectName"]    if toml["projectName"]
        result["apple.team.id"]    = toml["iosTeamId"]      if toml["iosTeamId"]
      end

      # 2. Overlay fork.properties (higher priority — developer-filled, gitignored)
      if File.exist?(fork_path)
        parse_props(fork_path).each { |k, v| result[k] = v }
      elsif File.exist?(props_path)
        # Fallback: local.properties written by syncForkConfig (strip fork. prefix)
        parse_props(props_path).each do |k, v|
          result[k.sub(/^fork\./, "")] = v if k.start_with?("fork.")
        end
      end

      result
    end

    def self.parse_props(path)
      props = {}
      File.readlines(path).each do |line|
        next if line.strip.start_with?("#", "!") || !line.include?("=")
        k, v = line.strip.split("=", 2)
        props[k.strip] = v&.strip
      end
      props
    end

    def self.parse_toml_versions(path)
      result = {}
      File.readlines(path).each do |line|
        trimmed = line.strip
        next if trimmed.start_with?("#") || !trimmed.include?("=")
        key, raw = trimmed.split("=", 2).map(&:strip)
        # Strip surrounding quotes, then inline comment
        value = raw.to_s.gsub(/\A"(.*?)"\z/, '\1').split(" #").first.to_s.strip
        result[key] = value unless value.empty?
      end
      result
    end

    FORK = load_fork_identity

    PROJECT_NAME      = FORK["project.name"] || "kmp-project-template"
    ORGANIZATION_NAME = ENV["ORGANIZATION_NAME"] || FORK["org.name"] || "Your Organization"

    # ── Stage fork values as local variables ─────────────────────────────────────
    _app_id        = FORK["app.id"] || "org.example.app"
    _contact_email = ENV["BETA_FEEDBACK_EMAIL"]  || FORK["org.email"]
    _marketing_url = ENV["APP_MARKETING_URL"]    || FORK["org.marketing.url"]
    _privacy_url   = ENV["APP_PRIVACY_URL"]      || FORK["org.privacy.url"]

    _team_id          = ENV["APPLE_TEAM_ID"]    || FORK["apple.team.id"]
    _match_git_url    = ENV["MATCH_GIT_URL"]    || FORK["apple.match.git.url"]
    _match_git_branch = ENV["MATCH_GIT_BRANCH"] || "master"

    _testflight_groups = if ENV["TESTFLIGHT_GROUPS"]&.length&.positive?
      ENV["TESTFLIGHT_GROUPS"].split(",")
    elsif FORK["apple.tf.groups"]&.length&.positive?
      FORK["apple.tf.groups"].split(",")
    else
      []
    end

    _tf_contact_email = ENV["TESTFLIGHT_CONTACT_EMAIL"]   || FORK["org.email"]
    _tf_first_name    = ENV["TESTFLIGHT_FIRST_NAME"]      || FORK["org.first.name"]
    _tf_last_name     = ENV["TESTFLIGHT_LAST_NAME"]       || FORK["org.last.name"]
    _tf_phone         = ENV["TESTFLIGHT_PHONE"]           || FORK["org.phone"]
    _as_first_name    = ENV["APPSTORE_REVIEW_FIRST_NAME"] || FORK["org.first.name"]
    _as_last_name     = ENV["APPSTORE_REVIEW_LAST_NAME"]  || FORK["org.last.name"]
    _as_phone         = ENV["APPSTORE_REVIEW_PHONE"]      || FORK["org.phone"]
    _as_email         = ENV["APPSTORE_REVIEW_EMAIL"]      || FORK["org.email"]

    # ── Android ────────────────────────────────────────────────────────────────
    ANDROID = {
      package_name:        _app_id,
      play_store_json_key: BuildSecrets.for.path(:play_service_account),
      apk_paths: {
        prod: "cmp-android/build/outputs/apk/prod/release/cmp-android-prod-release.apk",
        demo: "cmp-android/build/outputs/apk/demo/release/cmp-android-demo-release.apk",
      },
      aab_path:  "cmp-android/build/outputs/bundle/prodRelease/cmp-android-prod-release.aab",
      keystore: {
        file:         ENV["ANDROID_STORE_FILE"]    || "upload_keystore.keystore",
        password:     ENV["ANDROID_STORE_PASSWORD"] || "",
        key_alias:    ENV["ANDROID_KEY_ALIAS"]     || "release-key",
        key_password: ENV["ANDROID_KEY_PASSWORD"]  || "",
      },
      firebase: {
        # ENV overrides: FIREBASE_ANDROID_PROD_APP_ID / FIREBASE_ANDROID_DEMO_APP_ID / FIREBASE_GROUPS
        prod_app_id: ENV["FIREBASE_ANDROID_PROD_APP_ID"] || FORK["firebase.android.prod.app.id"],
        demo_app_id: ENV["FIREBASE_ANDROID_DEMO_APP_ID"] || FORK["firebase.android.demo.app.id"],
        groups:      (ENV["FIREBASE_GROUPS"] || FORK["firebase.groups"])&.split(","),
      },
    }.freeze

    # ── iOS app-specific ───────────────────────────────────────────────────────
    IOS = {
      app_identifier: _app_id,
      firebase: {
        # ENV overrides: FIREBASE_IOS_APP_ID / FIREBASE_GROUPS
        app_id: ENV["FIREBASE_IOS_APP_ID"] || FORK["firebase.ios.app.id"],
        groups: (ENV["FIREBASE_GROUPS"] || FORK["firebase.groups"])&.split(","),
      },
      project_path:    "cmp-ios/iosApp.xcodeproj",
      workspace_path:  "cmp-ios/iosApp.xcworkspace",
      plist_path:      "cmp-ios/iosApp/Info.plist",
      scheme:          "iosApp",
      output_name:     "iosApp.ipa",
      output_directory: "cmp-ios/build",
      # Canonical metadata location (moved from fastlane/metadata/ in sub-plan 14).
      metadata_path:          "deployment/ios/appstore/metadata",
      age_rating_config_path: "deployment/ios/appstore/metadata/app_store_rating_config.json",
      primary_locale:         "en-GB",
      version_number:         "1.0.0",
    }.freeze

    # ── iOS shared (org-level) ─────────────────────────────────────────────────
    IOS_SHARED = {
      # ENV override: APPLE_TEAM_ID
      team_id:    _team_id,
      ci_provider: "circleci",
      app_store_connect: {
        # ENV overrides: APPSTORE_KEY_ID / APPSTORE_ISSUER_ID / APPSTORE_KEY_PATH
        key_id:       ENV["APPSTORE_KEY_ID"]    || "",
        issuer_id:    ENV["APPSTORE_ISSUER_ID"] || "",
        key_filepath: ENV["APPSTORE_KEY_PATH"]  || "secrets/live/apple/appstore/AuthKey.p8",
      },
      code_signing: {
        match_type:            "adhoc",
        # ENV overrides: MATCH_GIT_URL / MATCH_GIT_BRANCH / MATCH_GIT_PRIVATE_KEY
        match_git_url:         _match_git_url,
        match_git_branch:      _match_git_branch,
        match_git_private_key: ENV["MATCH_GIT_PRIVATE_KEY"] || "./secrets/live/apple/match/match_ci_key",
        provisioning_profiles: {
          adhoc:    "match AdHoc #{_app_id}",
          appstore: "match AppStore #{_app_id}",
        },
      },
      testflight: {
        beta_app_review_info: {
          # ENV overrides: TESTFLIGHT_CONTACT_EMAIL / TESTFLIGHT_FIRST_NAME / TESTFLIGHT_LAST_NAME / TESTFLIGHT_PHONE
          contact_email:      _tf_contact_email,
          contact_first_name: _tf_first_name,
          contact_last_name:  _tf_last_name,
          contact_phone:      _tf_phone,
          demo_account_name:     ENV["TESTFLIGHT_DEMO_EMAIL"]    || "",
          demo_account_password: ENV["TESTFLIGHT_DEMO_PASSWORD"] || "",
          notes: "Thank you for reviewing our app!",
        },
        # ENV override: BETA_FEEDBACK_EMAIL
        beta_app_feedback_email:           _contact_email,
        beta_app_description:              "Kotlin Multiplatform mobile application",
        demo_account_required:             false,
        distribute_external:               true,
        notify_external_testers:           true,
        # ENV override: TESTFLIGHT_GROUPS (comma-separated); fork.properties: apple.tf.groups
        groups:                            _testflight_groups,
        skip_submission:                   false,
        skip_waiting_for_build_processing: true,
        submit_beta_review:                true,
        expire_previous_builds:            false,
        reject_build_waiting_for_review:   false,
        wait_processing_interval:          30,
        wait_processing_timeout_duration:  3600,
        uses_non_exempt_encryption:        false,
        localized_app_info: {
          # ENV overrides: BETA_FEEDBACK_EMAIL / APP_MARKETING_URL / APP_PRIVACY_URL
          "default" => {
            feedback_email:     _contact_email,
            marketing_url:      _marketing_url,
            privacy_policy_url: _privacy_url,
            description:        "Kotlin Multiplatform mobile application",
          },
          "en-GB" => {
            feedback_email:     _contact_email,
            marketing_url:      _marketing_url,
            privacy_policy_url: _privacy_url,
            description:        "Kotlin Multiplatform mobile application",
          },
        },
      },
      appstore: {
        app_review_information: {
          # ENV overrides: APPSTORE_REVIEW_FIRST_NAME / APPSTORE_REVIEW_LAST_NAME /
          #                APPSTORE_REVIEW_PHONE / APPSTORE_REVIEW_EMAIL
          first_name:    _as_first_name,
          last_name:     _as_last_name,
          phone_number:  _as_phone,
          email_address: _as_email,
          demo_user:     ENV["APPSTORE_DEMO_EMAIL"]    || "",
          demo_password: ENV["APPSTORE_DEMO_PASSWORD"] || "",
          notes:         "Thank you for reviewing our app!",
        },
        submit_for_review:                 true,
        automatic_release:                 true,
        phased_release:                    false,
        skip_app_version_update:           false,
        reject_if_possible:                true,
        force:                             true,
        precheck_include_in_app_purchases: false,
        run_precheck_before_submit:        true,
        submission_information: {
          add_id_info_uses_idfa:                          false,
          add_id_info_limits_tracking:                    false,
          add_id_info_serves_ads:                         false,
          add_id_info_tracks_action:                      false,
          add_id_info_tracks_install:                     false,
          content_rights_has_rights:                      true,
          content_rights_contains_third_party_content:    false,
          export_compliance_platform:                     "ios",
          export_compliance_compliance_required:          false,
          export_compliance_encryption_updated:           false,
          export_compliance_app_type:                     nil,
          export_compliance_uses_encryption:              false,
          export_compliance_is_exempt:                    true,
          export_compliance_contains_third_party_cryptography: false,
          export_compliance_contains_proprietary_cryptography: false,
          export_compliance_available_on_french_store:    true,
        },
      },
    }.freeze

    # ── Shared (both platforms) ────────────────────────────────────────────────
    SHARED = {
      firebase_service_credentials: BuildSecrets.for.path(:firebase_service_account),
    }.freeze

    # ── Helpers ────────────────────────────────────────────────────────────────
    def self.android_package_name = ANDROID[:package_name]
    def self.ios_bundle_identifier = IOS[:app_identifier]
    def self.firebase_credentials_file = SHARED[:firebase_service_credentials]
    def self.ios_config = IOS.merge(IOS_SHARED)
  end

  # ── AndroidConfig (mirrors pre-restructure fastlane-config/android_config.rb) ──

  module AndroidConfig
    # Artifact paths derive by convention via VariantResolver (D9/AC-3) — the
    # former per-flavor BUILD_PATHS constant has been removed.

    FIREBASE = {
      prod: {
        appId:            ProjectConfig::ANDROID[:firebase][:prod_app_id],
        groups:           ProjectConfig::ANDROID[:firebase][:groups],
        serviceCredsFile: ProjectConfig::SHARED[:firebase_service_credentials],
      }.freeze,
      demo: {
        appId:            ProjectConfig::ANDROID[:firebase][:demo_app_id],
        groups:           ProjectConfig::ANDROID[:firebase][:groups],
        serviceCredsFile: ProjectConfig::SHARED[:firebase_service_credentials],
      }.freeze,
    }.freeze

    def self.get_signing_config(options = {})
      {
        storeFile:     options[:store_file]     || ENV["ANDROID_STORE_FILE"]     || ProjectConfig::ANDROID[:keystore][:file],
        storePassword: options[:store_password] || ENV["ANDROID_STORE_PASSWORD"] || ProjectConfig::ANDROID[:keystore][:password],
        keyAlias:      options[:key_alias]      || ENV["ANDROID_KEY_ALIAS"]      || ProjectConfig::ANDROID[:keystore][:key_alias],
        keyPassword:   options[:key_password]   || ENV["ANDROID_KEY_PASSWORD"]   || ProjectConfig::ANDROID[:keystore][:key_password],
      }
    end
  end

  # ── IosConfig (mirrors pre-restructure fastlane-config/ios_config.rb) ─────────

  module IosConfig
    BUILD_CONFIG = {
      app_identifier:   ProjectConfig::IOS[:app_identifier],
      project_path:     ProjectConfig::IOS[:project_path],
      workspace_path:   ProjectConfig::IOS[:workspace_path],
      plist_path:       ProjectConfig::IOS[:plist_path],
      scheme:           ProjectConfig::IOS[:scheme],
      output_name:      ProjectConfig::IOS[:output_name],
      output_directory: ProjectConfig::IOS[:output_directory],
      version_number:   ProjectConfig::IOS[:version_number],
      metadata_path:    ProjectConfig::IOS[:metadata_path],
      app_rating_config_path: ProjectConfig::IOS[:age_rating_config_path],
      primary_locale:   ProjectConfig::IOS[:primary_locale],
      team_id:          ProjectConfig::IOS_SHARED[:team_id],
      ci_provider:      ProjectConfig::IOS_SHARED[:ci_provider],
      key_id:           ProjectConfig::IOS_SHARED[:app_store_connect][:key_id],
      issuer_id:        ProjectConfig::IOS_SHARED[:app_store_connect][:issuer_id],
      key_filepath:     ProjectConfig::IOS_SHARED[:app_store_connect][:key_filepath],
      match_type:                    ProjectConfig::IOS_SHARED[:code_signing][:match_type],
      match_git_private_key:         ProjectConfig::IOS_SHARED[:code_signing][:match_git_private_key],
      git_url:                       ProjectConfig::IOS_SHARED[:code_signing][:match_git_url],
      git_branch:                    ProjectConfig::IOS_SHARED[:code_signing][:match_git_branch],
      provisioning_profile_name:     ProjectConfig::IOS_SHARED[:code_signing][:provisioning_profiles][:adhoc],
      provisioning_profile_appstore: ProjectConfig::IOS_SHARED[:code_signing][:provisioning_profiles][:appstore],
      # Firebase (iOS-specific)
      firebase_app_id:    ProjectConfig::IOS[:firebase][:app_id],
      firebase_groups:    ProjectConfig::IOS[:firebase][:groups],
      firebase_creds_file: ProjectConfig::SHARED[:firebase_service_credentials],
    }.freeze

    TESTFLIGHT_CONFIG = ProjectConfig::IOS_SHARED[:testflight].freeze
    APPSTORE_CONFIG   = ProjectConfig::IOS_SHARED[:appstore].freeze
  end

  # ── Module-level helpers (mirrors pre-restructure fastlane/config/config_helpers.rb) ──

  def self.get_android_signing_config(options = {})
    AndroidConfig.get_signing_config(options)
  end

  def self.get_firebase_config(platform, type = :prod)
    case platform
    when :android
      app_id = type == :prod ? AndroidConfig::FIREBASE[:prod][:appId] : AndroidConfig::FIREBASE[:demo][:appId]
      {
        appId:            ENV["FIREBASE_ANDROID_APP_ID"] || app_id,
        serviceCredsFile: ENV["FIREBASE_SERVICE_CREDS_FILE"] || AndroidConfig::FIREBASE[:prod][:serviceCredsFile],
        groups:           (ENV["FIREBASE_GROUPS"] || AndroidConfig::FIREBASE[:prod][:groups]&.join(","))&.split(","),
      }
    when :ios
      {
        appId:            ENV["FIREBASE_IOS_APP_ID"]         || IosConfig::BUILD_CONFIG[:firebase_app_id],
        serviceCredsFile: ENV["FIREBASE_SERVICE_CREDS_FILE"] || IosConfig::BUILD_CONFIG[:firebase_creds_file],
        groups:           (ENV["FIREBASE_GROUPS"] || IosConfig::BUILD_CONFIG[:firebase_groups]&.join(","))&.split(","),
      }
    end
  end
end
