/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.base.network

import io.github.jan.supabase.SupabaseClient
import io.github.jan.supabase.createSupabaseClient
import io.github.jan.supabase.logging.LogLevel
import io.github.jan.supabase.postgrest.Postgrest
import io.github.jan.supabase.postgrest.postgrest

/**
 * Generic Supabase client wrapper for KMP projects.
 *
 * This class provides a reusable Supabase client setup with:
 * - Lazy initialization of Supabase client
 * - Configurable logging level
 * - Direct access to Postgrest for queries
 *
 * ## Usage
 *
 * ```kotlin
 * // Create credentials (typically from generated SupabaseCredentials object)
 * val configClient = SupabaseConfigClient(
 *     credentials = SupabaseCredentials, // Generated by SupabaseConfigConventionPlugin
 *     logLevel = LogLevel.DEBUG,
 * )
 *
 * // Use the client for queries
 * if (configClient.isConfigured) {
 *     val result = configClient.postgrest
 *         .from("app_config")
 *         .select()
 *         .decodeSingle<MyConfig>()
 * }
 * ```
 *
 * @param credentials The Supabase credentials (URL and anon key).
 * @param logLevel The logging level for Supabase client. Defaults to INFO.
 */
class SupabaseConfigClient(
    private val credentials: SupabaseCredentials,
    private val logLevel: LogLevel = LogLevel.INFO,
) {
    /**
     * Lazily initialized Supabase client.
     * Only created when first accessed.
     */
    val client: SupabaseClient by lazy {
        createSupabaseClient(
            supabaseUrl = credentials.url,
            supabaseKey = credentials.anonKey,
        ) {
            defaultLogLevel = logLevel
            install(Postgrest)
        }
    }

    /**
     * Direct access to Postgrest for database operations.
     */
    val postgrest get() = client.postgrest

    /**
     * Checks if Supabase is properly configured.
     *
     * @return true if credentials are valid, false otherwise.
     */
    val isConfigured: Boolean
        get() = credentials.isConfigured
}

/**
 * Interface for Supabase credentials.
 *
 * Implement this interface to provide Supabase URL and anon key
 * from your project's build configuration or secrets.
 *
 * ## Generated Implementation
 *
 * If using the SupabaseConfigConventionPlugin, credentials are
 * automatically generated from `secrets/supabaseCredentialsFile.json`:
 *
 * ```kotlin
 * // Auto-generated SupabaseCredentials object
 * object SupabaseCredentials : kpt.core.base.network.SupabaseCredentials {
 *     override val url = "https://your-project.supabase.co"
 *     override val anonKey = "your-anon-key"
 * }
 * ```
 *
 * ## Manual Implementation
 *
 * ```kotlin
 * object MySupabaseCredentials : SupabaseCredentials {
 *     override val url: String = BuildConfig.SUPABASE_URL
 *     override val anonKey: String = BuildConfig.SUPABASE_ANON_KEY
 * }
 * ```
 */
interface SupabaseCredentials {
    /**
     * The Supabase project URL.
     * Example: "https://your-project.supabase.co"
     */
    val url: String

    /**
     * The Supabase anon (public) key.
     * This key is safe to use in client-side code.
     */
    val anonKey: String

    /**
     * Checks if the credentials are properly configured.
     * Returns false if URL or key contain placeholder values.
     */
    val isConfigured: Boolean
        get() = url.isNotBlank() &&
            anonKey.isNotBlank() &&
            !url.contains("YOUR_") &&
            !anonKey.contains("YOUR_") &&
            url.startsWith("https://")
}
