/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database

import androidx.room3.AutoMigration
import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import kpt.core.database.infra.dao.BookkeeperDao
import kpt.core.database.infra.dao.DraftDao
import kpt.core.database.infra.dao.FetchedAtDao
import kpt.core.database.infra.entity.BookkeeperEntity
import kpt.core.database.infra.entity.DraftEntity
import kpt.core.database.infra.entity.FetchedAtEntity
import kpt.core.database.wallet.account.SavingAccountDetailDao
import kpt.core.database.wallet.account.SavingAccountDetailEntity
import kpt.core.database.wallet.beneficiary.BeneficiaryDao
import kpt.core.database.wallet.beneficiary.BeneficiaryEntity
import kpt.core.database.wallet.bill.BillDao
import kpt.core.database.wallet.bill.BillEntity
import kpt.core.database.wallet.biller.BillerDao
import kpt.core.database.wallet.biller.BillerEntity
import kpt.core.database.wallet.client.ClientDetailDao
import kpt.core.database.wallet.client.ClientDetailEntity
import kpt.core.database.wallet.invoice.InvoiceDao
import kpt.core.database.wallet.invoice.InvoiceEntity
import kpt.core.database.wallet.linkableaccount.LinkableAccountDao
import kpt.core.database.wallet.linkableaccount.LinkableAccountEntity
import kpt.core.database.wallet.notification.NotificationDao
import kpt.core.database.wallet.notification.NotificationEntity
import kpt.core.database.wallet.office.OfficeDao
import kpt.core.database.wallet.office.OfficeEntity
import kpt.core.database.wallet.pocket.PocketDao
import kpt.core.database.wallet.pocket.PocketEntity
import kpt.core.database.wallet.recentpayee.RecentPayeeDao
import kpt.core.database.wallet.recentpayee.RecentPayeeEntity
import kpt.core.database.wallet.savedcards.SavedCardDao
import kpt.core.database.wallet.savedcards.SavedCardEntity
import kpt.core.database.wallet.selfaccounts.SelfAccountDao
import kpt.core.database.wallet.selfaccounts.SelfAccountEntity
import kpt.core.database.wallet.standinginstruction.StandingInstructionDao
import kpt.core.database.wallet.standinginstruction.StandingInstructionEntity
import kpt.core.database.wallet.transaction.TransactionDao
import kpt.core.database.wallet.transaction.TransactionEntity

/**
 * KSP-generated constructor bridge for [AppDatabase].
 *
 * Room 3 requires an `expect object` annotated via [@ConstructedBy][ConstructedBy] so that
 * the KSP compiler plugin can generate a platform-specific `actual object` containing the
 * `AppDatabase_Impl` instantiation logic.
 */
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/**
 * Root Room 3 database for the application.
 *
 * This is a **commonMain** definition that works across all Kotlin Multiplatform targets
 * (Android, Desktop/JVM, iOS/Native, JS, WasmJS). Platform-specific database creation
 * is handled by [kpt.core.base.database.AppDatabaseFactory] in each platform's
 * DI module — see [kpt.core.database.di.DatabaseModule].
 *
 * Room 3 uses the [ConstructedBy] annotation to delegate instance creation to
 * [AppDatabaseConstructor], whose `actual` implementation is generated by KSP on
 * every target.
 *
 * ## Schema history
 * | Version | Change |
 * |---------|--------|
 * | v1 → v2 | Phase-4 store pilots — adds `wallet_transactions` (LEDGER, GOAL D13) + `wallet_autopay_bills` (OFFLINE_LOCAL_ONLY, GOAL D12). Purely additive; auto-migration handles it. |
 * | v2 → v3 | Phase-5 Batch-1 read-cache stores — adds `wallet_saving_account_details` (SINGLE-ROW-PER-KEY, GOAL D13), `wallet_beneficiaries` (LEDGER, GOAL D13), `wallet_saved_cards` (LEDGER, GOAL D13). Purely additive; auto-migration handles it. |
 * | v3 → v4 | Phase-5 Batch-2 read-cache stores — adds `wallet_invoices` (LEDGER, GOAL D13), `wallet_notifications` (LEDGER, GOAL D13), `wallet_client_details` (SINGLE-ROW-PER-KEY, GOAL D13), `wallet_pockets` (LEDGER, GOAL D13; replaces the in-memory `detailedPocketCache` MutableStateFlow in `PocketRepositoryImp`). Purely additive; auto-migration handles it. |
 * | v4 → v5 | Phase-5 Batch-3 read-cache stores — adds `wallet_standing_instructions` (LEDGER, GOAL D13), `wallet_offices` (LEDGER — global singleton-keyed reference data, GOAL D13), `wallet_self_accounts` (LEDGER, GOAL D13). Purely additive; auto-migration handles it. Batch-3 also delivers the `receipt` feature WITHOUT its own store (per GOAL D13 — reads off the existing `wallet_transactions` LEDGER; see `ReceiptViewModel` KDoc). |
 * | v5 → v6 | Phase-5 Batch-4 offline / local-derived stores — adds `wallet_autopay_billers` (OFFLINE_LOCAL_ONLY — user-authored biller catalog, GOAL D12; mirrors the `wallet_autopay_bills` shape) and `wallet_recent_payees` (LOCAL-DERIVED — persist-on-derive cache of recent-payees derived from transaction history, replaces the N+1 walk in `RecentPayeeRepositoryImpl` on cache hits, GOAL D12/D13 hybrid). Purely additive; auto-migration handles it. Batch-4 also folds in the store-native `getAccountAndBeneficiaryListScreen` combinator in `SelfServiceRepository` (no new table — uses the existing `wallet_beneficiaries` + the network account stream through `combineScreenStates`), and records a STUB verdict for the `merchants` feature (no server counterpart today; no store emitted). |
 * | v6 → v7 | manage-pocket linkable-accounts Store5 migration — adds `wallet_linkable_accounts` (LEDGER — derived read-cache of accounts a client CAN link into a pocket, GOAL D13). Replaces upstream PR #2057's multiplatform-settings `linkable_accounts` cache in `PocketPreferencesDataSource`; this branch's Store5 architecture serves the same read offline-first through Room SoT + CACHE_FIRST_SWR (matches `PocketStore` / `BeneficiaryStore` / `SelfAccountsStore` recipe). Purely additive; auto-migration handles it. |
 *
 * ## Stale-schema-JSON note
 *
 * The `core/database/schemas/kpt.core.database.AppDatabase/` directory carries schema
 * exports 1.json — 10.json inherited from the template baseline. Only `1.json` is
 * valid for THIS fork (it exports the 3 infra tables — `store_bookkeeper`,
 * `framework_fetched_at`, `framework_submit_drafts`). Files 2.json..10.json describe
 * the template's demo tables and DO NOT match the fork's fresh baseline; they should
 * be pruned before the next build so KSP regenerates 2.json + 3.json cleanly for THIS
 * pilot and this Phase-5 batch. (Doing the prune here would be a build-side change;
 * this Batch-1 pass leaves them alone and flags the follow-up in the return payload.)
 */
@Database(
    entities = [
        // infra (framework) — always kept
        BookkeeperEntity::class,
        FetchedAtEntity::class,
        DraftEntity::class,
        // Phase-4 store pilots (v2) — fork-owned tables
        TransactionEntity::class,
        BillEntity::class,
        // Phase-5 Batch-1 read-cache stores (v3) — fork-owned tables
        SavingAccountDetailEntity::class,
        BeneficiaryEntity::class,
        SavedCardEntity::class,
        // Phase-5 Batch-2 read-cache stores (v4) — fork-owned tables
        InvoiceEntity::class,
        NotificationEntity::class,
        ClientDetailEntity::class,
        PocketEntity::class,
        // Phase-5 Batch-3 read-cache stores (v5) — fork-owned tables
        StandingInstructionEntity::class,
        OfficeEntity::class,
        SelfAccountEntity::class,
        // Phase-5 Batch-4 offline / local-derived stores (v6) — fork-owned tables
        BillerEntity::class,
        RecentPayeeEntity::class,
        // manage-pocket linkable-accounts Store5 migration (v7) — fork-owned table
        LinkableAccountEntity::class,
    ],
    version = AppDatabase.VERSION,
    exportSchema = true,
    autoMigrations = [
        // v1 → v6: consolidated purely-additive migration covering every batch
        // (Phase-4 stores, Phase-5 Batches 1/2/3/4). Original per-batch AutoMigrations
        // 1→2, 2→3, 3→4, 4→5, 5→6 required intermediate schema JSONs (2..5.json) that
        // were never exported during phased development. Since every step is purely
        // additive (only `CREATE TABLE IF NOT EXISTS …` — no column drops/renames/type
        // changes on the v1 tables `bookkeeper`, `fetched_at`, `draft`), collapsing
        // them into a single 1→6 diff is safe: Room diffs schemas/1.json vs
        // schemas/6.json and emits CREATE TABLE for the 14 net-new wallet_* tables.
        // Any device that shipped on an intermediate version (2..5) is caught by the
        // .addMigrations(...) fallback wired in DatabaseModule (see MIGRATION_1_6).
        AutoMigration(from = 1, to = 6),
        // v6 → v7: purely-additive migration for the manage-pocket linkable-accounts
        // Store5 migration — adds ONE net-new table `wallet_linkable_accounts`. Room
        // diffs schemas/6.json vs schemas/7.json and emits `CREATE TABLE
        // wallet_linkable_accounts (...)`. Safe as a standalone AutoMigration
        // because no v1..v6 column is altered (only a new table appears in v7).
        AutoMigration(from = 6, to = 7),
    ],
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {

    // infra (framework) — always kept
    abstract val bookkeeperDao: BookkeeperDao
    abstract val fetchedAtDao: FetchedAtDao
    abstract val draftDao: DraftDao

    // Phase-4 store pilots — fork-owned wallet DAOs
    abstract val transactionDao: TransactionDao
    abstract val billDao: BillDao

    // Phase-5 Batch-1 read-cache stores — fork-owned wallet DAOs
    abstract val savingAccountDetailDao: SavingAccountDetailDao
    abstract val beneficiaryDao: BeneficiaryDao
    abstract val savedCardDao: SavedCardDao

    // Phase-5 Batch-2 read-cache stores — fork-owned wallet DAOs
    abstract val invoiceDao: InvoiceDao
    abstract val notificationDao: NotificationDao
    abstract val clientDetailDao: ClientDetailDao
    abstract val pocketDao: PocketDao

    // Phase-5 Batch-3 read-cache stores — fork-owned wallet DAOs
    abstract val standingInstructionDao: StandingInstructionDao
    abstract val officeDao: OfficeDao
    abstract val selfAccountDao: SelfAccountDao

    // Phase-5 Batch-4 offline / local-derived stores — fork-owned wallet DAOs
    abstract val billerDao: BillerDao
    abstract val recentPayeeDao: RecentPayeeDao

    // manage-pocket linkable-accounts Store5 migration — fork-owned wallet DAO
    abstract val linkableAccountDao: LinkableAccountDao

    companion object {
        // Bumped from 6 → 7 for the manage-pocket linkable-accounts Store5
        // migration. Introduces ONE net-new table (`wallet_linkable_accounts`
        // — LEDGER derived read-cache of accounts a client CAN link into a
        // pocket) that REPLACES upstream PR #2057's multiplatform-settings
        // `linkable_accounts` cache in `PocketPreferencesDataSource`.
        // Additive migration (see @AutoMigration(from = 6, to = 7) above).
        const val VERSION = 7

        /** Fork-unique on-disk DB filename — single source of truth is [DatabaseConfig.NAME]
         *  (appId-derived, regenerated by `syncForkConfig`). All platform builders read this. */
        const val DATABASE_NAME = DatabaseConfig.NAME
    }
}
