/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database

/** Fork-unique database naming — generated by syncForkConfig from app-profile/app.yaml. */
object DatabaseConfig {
    /** On-disk SQLite file name (appId-derived). */
    const val NAME = "org_mifospay.db"

    /** Desktop (JVM) data directory under the OS app-data root (app_name-derived). */
    const val DESKTOP_DIR_NAME = "MifosPay"
}
