name: Multi-Platform(Re-Usable) App Build and Publish

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
          - internal  # For internal testing purposes
          - beta      # For beta testing with external testers
        default: internal
        description: Release Type

      publish_android:
        type: boolean
        default: false
        description: Publish Android App On Play Store

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  multi_platform_build_and_publish:
    name: Build Android Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Publish Android App
        uses: niyajali/mifos-mobile-github-actions/.github/workflows/multi_platform_build_and_publish.yaml@main
        secrets: inherit
        with:
          release_type: ${{ inputs.release_type }}
          publish_android: ${{ inputs.publish_android }}
          android_package_name: 'mifospay-android'